spring.application.name=studyplanmgmt
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://104.214.185.131:3306/studyplan?createDatabaseIfNotExist=true
spring.datasource.username=vn
spring.datasource.password=hcmiu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.jpa.show-sql: true
#     url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/studyplan
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin


#Github
spring.security.oauth2.client.registration.github.client-id=Ov23liRP17F2bT8zKKU5
spring.security.oauth2.client.registration.github.client-secret=13765c2234d1b12f9e3cf29ca8de4625dab961f9
spring.security.oauth2.client.registration.github.scope=read:user,user:email

#Google
spring.security.oauth2.client.registration.google.client-id=512205702752-b7772ic2ef7e7rvot65k2cj1n3ce1v7a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/{registrationId}

#Front
app.frontend.url=http://localhost:3000


# server:
#   port: 8080

# spring:
#   application:
#     name: USER-SERVICE

#   jpa:
#     hibernate:
#       ddl-auto: update
#     database-platform: org.hibernate.dialect.MySQLDialect 

#   datasource:
#     url: jdbc:mysql://104.214.185.131:3306/studyplan
#     username: vn
#     password: hcmiu
#     driver-class-name: com.mysql.cj.jdbc.Driver
    