# Generated by Django 5.1.4 on 2024-12-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0004_task_taskmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
