# Generated by Django 5.1.4 on 2025-01-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0005_task_is_completed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventMember",
        ),
    ]
